risurei2/src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_places;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="participationEvents")
     */
    private $entrant;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $placesRemain;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $place;

    public function __construct()
    {
        $this->entrant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEventDate(): ?string
    {
        return $this->event_date;
    }

    public function setEventDate(string $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nb_places;
    }

    public function setNbPlaces(int $nb_places): self
    {
        $this->nb_places = $nb_places;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getEntrant(): Collection
    {
        return $this->entrant;
    }

    public function addEntrant(User $entrant): self
    {
        if (!$this->entrant->contains($entrant)) {
            $this->entrant[] = $entrant;
        }

        return $this;
    }

    public function removeEntrant(User $entrant): self
    {
        $this->entrant->removeElement($entrant);

        return $this;
    }

    public function getPlacesRemain(): ?int
    {
        return $this->placesRemain;
    }

    public function setPlacesRemain(?int $placesRemain): self
    {
        $this->placesRemain = $placesRemain;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPlace(): ?int
    {
        return $this->place;
    }

    public function setPlace(?int $place): self
    {
        $this->place = $place;

        return $this;
    }
}

risurei2/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Event;
use App\Entity\User;
use App\Form\BlogType;
use App\Form\EventType;
use App\Repository\BlogRepository;
use App\Repository\EventRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    /**
     * @Route("/evenements", name="show_events")
     */
    public function show_events(EventRepository $repo): Response
    {


        $events =  $repo->findAll();
        return $this->render('home/show_events.html.twig', [
            'events' => $events,
        ]);
    }

    /**
     * @Route("/evenement/create", name="create")
     * @Route("/evenement/{id}/edit", name="edit")
     */
    public function form(Event $event = null, Request $request, ManagerRegistry $manager)
    {

        if (empty($this->getUser())) {

            return $this->redirectToRoute('login');
        }


        if (!$event) {
            $event = new Event();
        }

        $form = $this->createForm(EventType::class, $event);

        $form->handleRequest($request);
        dump($form);

        if ($form->isSubmitted() && $form->isValid()) {
            // if (!$event->getId()) {
            $event->setCreatedAt(new \DateTime());
            $event->setUser($this->getUser());
            $event->setPlacesRemain($event->getNbPlaces());
            $event->setImage('new image');
            $event->setNbPlaces(1);
            $event->setEventDate('ok');
            // }

            $em = $manager->getManager();
            $em->persist($event);
            $em->flush();


            return $this->redirectToRoute('show_events', ['id' => $event->getId()]);
        }

        return $this->render('home/create.html.twig', [
            'form' => $form->createView(),
            'editMode' => $event->getId() !== null
        ]);
    }


    /**
     * @Route("/evenement/{id}", name="show")
     */
    public function show(Event $event)
    {

        return $this->render('home/show.html.twig', [
            'event' => $event
        ]);
    }

    /**
     * @Route("/evenement/{id}/delete", name="delete")
     */
    public function delete(EventRepository $repo, Event $event, ManagerRegistry $manager,)
    {

        $em = $manager->getManager();
        $em->remove($event);
        $em->flush();


        $events =  $repo->findAll();

        return $this->render('home/show_events.html.twig', [
            'events' => $events
        ]); //TODO : rediriger vers la liste des annonces
    }

    /**
     * @Route("/evenement/{id}/inscription", name="inscription_event")
     * @Route("/evenement/{id}/desinscription", name="desinscription_event")
     */
    public function inscriptionEvent(Event $event, Request $request, ManagerRegistry $manager)
    {


        if (empty($this->getUser())) {

            return $this->redirectToRoute('login');
        };

        $places = $event->getPlacesRemain();

        $getUser = $this->getUser();

        $entrant = $event->getEntrant();

        // dump($user->getParticipationEvents($getUser));

        // if (!$event->getEntrant($getUser)) {
        if ($event->getPlacesRemain() > 0) {
            $event->setPlacesRemain($places - 1);
            $event->addEntrant($getUser);
        } else {
            return $this->render('home/show.html.twig', [
                'plus_de_place' => 'Désolé l\'évènement est déjà complet.',
                'event' => $event,
                // 'entrant' => $entrant
            ]);
        }

        $em = $manager->getManager();
        $em->persist($event);
        $em->flush();
        // } else {
        //     $event->setPlacesRemain($places + 1);
        //     $event->removeEntrant($user);
        //     return $this->render('home/show.html.twig', [
        //         'inscrit' => 'Vous êtes déjà inscrit à cet evenement',
        //         'event' => $event,
        //         'entrant' => $entrant
        //     ]);
        // }


        return $this->render('home/show.html.twig', [
            'event' => $event,
            // 'entrant' => $entrant
        ]);
    }

    /**
     * @Route("/compte", name="account")
     */
    public function compte(EventRepository $eventRepository)
    {
        $id_event = $this->getUser();

        dump($id_event);

        $events = $eventRepository->findAllById($id_event);
        return $this->render('home/account.html.twig', [
            'eves' => $events,
            'user' => $id_event
        ]);
    }

    /**
     * @Route("/blog", name="blog")
     */
    public function blog(BlogRepository $repo)
    {

        $blog = $repo->findAll();
        return $this->render('home/blog.html.twig', [
            'blogs' => $blog
        ]);
    }


    /**
     * @Route("/blog/create", name="create_blog")
     * @Route("/blog/{id}/edit", name="edit_blog")
     */
    public function formBlog(Blog $blog = null, Request $request, ManagerRegistry $manager)
    {

        if (empty($this->getUser())) {

            return $this->redirectToRoute('login');
        }


        if (!$blog) {
            $blog = new Blog();
        }

        $formBlog = $this->createForm(BlogType::class, $blog);

        $formBlog->handleRequest($request);
        dump($formBlog);

        if ($formBlog->isSubmitted() && $formBlog->isValid()) {

            $blog->setCreatedAt(new \DateTime());

            $em = $manager->getManager();
            $em->persist($blog);
            $em->flush();


            return $this->redirectToRoute('blog_show', ['id' => $blog->getId()]);
        }

        return $this->render('home/create_blog.html.twig', [
            'form' => $formBlog->createView(),
            'editMode' => $blog->getId() !== null
        ]);
    }

    /**
     * @Route("/blog/{id}", name="blog_show")
     */
    public function show_blog(BlogRepository $repo, Blog $blog)
    {
        return $this->render('home/blog_show.html.twig', [
            'blog' => $blog
        ]);
    }

    /**
     * @Route("/blog/{id}/delete", name="delete_blog")
     */
    public function deleteArticle(BlogRepository $repo, Blog $blog, ManagerRegistry $manager,)
    {

        $em = $manager->getManager();
        $em->remove($blog);
        $em->flush();


        $blogs =  $repo->findAll();

        return $this->render('home/blog.html.twig', [
            'blogs' => $blogs
        ]); //TODO : rediriger vers la liste des articles
    }

    /**
     * @Route("/rgpd", name="rgpd")
     */
    public function rgpd()
    {
        return $this->render('home/rgpd.html.twig');
    }
}

risurei2/templates/home/account.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<!-- This example requires Tailwind CSS v2.0+ -->
	<div class="relative bg-white pt-16 pb-20 px-4 sm:px-6 lg:pt-24 lg:pb-28 lg:px-8">
		<div class="absolute inset-0">
			<div class="bg-white h-1/3 sm:h-2/3"></div>
		</div>
		<div class="relative max-w-7xl mx-auto">
			<div class="text-center">
				<h1 class="text-3xl tracking-tight font-bold text-gray-900 sm:text-4xl sm:tracking-tight">Mon compte</h1>
			</div>
			{% if eves == null %}
				<!-- This example requires Tailwind CSS v2.0+ -->
				<div class="">
					<div class="max-w-7xl mx-auto text-center py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
						<p class="text-xl font-medium tracking-tight text-gray-900 sm:text-4xl sm:tracking-tight">
							<span class="block">Vous n'avez pas encore d'evenement</span>
							{# <span class="block">Start your free trial today.</span> #}
						</p>
						{% if app.user %}
							{% if app.user.administrateur == true %}
								<div class="mt-8 flex justify-center">
									<div class="inline-flex rounded-md shadow">
										<a href="{{ path('create') }}" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
											Créer un événement
										</a>
									</div>
								</div>
							{% endif %}
						{% endif %}
					</div>
				</div>

			{% else %}

				<div class="mt-12 max-w-lg mx-auto grid gap-5 lg:grid-cols-3 lg:max-w-none">

					{% for event in eves %}
						<div class="flex flex-col rounded-lg shadow-lg overflow-hidden">
							<a href="{{ path('show', {'id' : event.id}) }}">
								<div class="flex-shrink-0">
									<img class="h-48 w-full object-cover" src="https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80" alt="">
								</div>
								<div class="flex-1 bg-white p-6 flex flex-col justify-between">
									<div class="flex-1">
										<p class="text-sm font-medium text-orange-brand">
											<a href="#" class="hover:underline">
												event
											</a>
										</p>
										<a href="#" class="block mt-2">
											<p class="text-xl font-semibold text-gray-900">{{ event.title }}</p>
											<p class="mt-3 text-base text-gray-500">{{event.content | raw}}</p>
										</a>
									</div>
									<div class="mt-6 flex items-center">
										<div class="flex-shrink-0"></div>
										<div>
											<div class="flex space-x-1 text-sm text-gray-500">
												<time datetime="2020-03-16">
													{{event.eventDate }}
												</time>
												<span aria-hidden="true">
													&middot;
												</span>
												<span>
													{{event.nbPlaces}}
													places
												</span>
											</div>
										</div>
									</div>
								</div>
							</a>
						</div>
					{% endfor %}

				</div>

			{% endif %}

			<div class="rounded-md shadow mt-8">
				<a href="{{path('delete_user', {'id':user.id})}}" class="w-full flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-red-brand hover:bg-red-hover">
					Supprimer le compte
				</a>
			</div>
		</div>
	</div>

{% endblock %}

risurei2/templates/home/blog.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="relative bg-gray-50 pt-16 pb-20 px-4 sm:px-6 lg:pt-24 lg:pb-28 lg:px-8">
		<div class="absolute inset-0">
			<div class="bg-white h-1/3 sm:h-2/3"></div>
		</div>
		<div class="relative max-w-7xl mx-auto">
			<div class="text-center">
				<h2 class="text-3xl tracking-tight font-bold text-gray-900 sm:text-4xl sm:tracking-tight">Le blog</h2>
				{# <p class="mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa libero labore natus atque, ducimus sed.</p> #}
			</div>


			<div class="bg-white px-4 pt-16 pb-20 sm:px-6 lg:px-8 lg:pt-24 lg:pb-28">
				<div class="relative mx-auto max-w-lg divide-y-2 divide-gray-200 lg:max-w-7xl">
					<div>
						<h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Press</h2>
					</div>

					{% for blog in blogs %}
						<div class="mt-6 grid gap-16 pt-10 lg:grid-cols-2 lg:gap-x-5 lg:gap-y-12">
							<div>
								<p class="text-sm text-gray-500">
									<time datetime="2020-03-16">{{blog.createdAt | date('d/m/Y')}}</time>
								</p>
								<a href="#" class="mt-2 block">
									<p class="text-xl font-semibold text-gray-900">{{blog.title}}</p>
									<p class="mt-3 text-base text-gray-500">{{blog.title}}.</p>
								</a>
								<div class="mt-3">
									<a href="{{path('blog_show', {'id': blog.id})}}" class="text-base font-semibold text-orange-brand hover:text-orange-hover">Lire la suite</a>
								</div>
							</div>
						</div>

					{% endfor %}
				</div>
			</div>


		</div>
	</div>

{% endblock %}

risurei2/templates/home/blog_show.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<div class="relative overflow-hidden bg-white py-16">
		<div class="relative px-4 sm:px-6 lg:px-8">
			<div class="mx-auto max-w-prose text-lg">
				<h1>
					<span class="block text-center text-lg font-semibold text-orange-brand">Blog</span>
					<span class="mt-2 block text-center text-3xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl">{{blog.title}}</span>
				</h1>
				<p class="mt-8 text-xl leading-8 text-gray-500">{{blog.content}}.</p>
				<p class="mt-8 text-xl leading-8 text-gray-500">Posté le
					{{blog.createdAt | date('d/m/Y')}}
				</p>
				{% if app.user %}
					{% if app.user.administrateur == true %}
						<div class="grid grid-cols-2">
							<div class="rounded-md shadow">
								<a href="{{path('edit_blog', {'id':blog.id})}}" class="w-full flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md bg-white text-orange-brand hover:bg-gray-50">
									Modifier l'article
								</a>
							</div>
							<div class="rounded-md shadow ml-4">
								<a href="{{path('delete_blog', {'id':blog.id})}}" class="w-full flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md bg-red-brand text-white hover:bg-red-hover">
									Supprimer l'article
								</a>
							</div>
						</div>
					{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

risurei2/templates/home/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}


	<div class="text-center mt-10">
		<h1 class="text-3xl tracking-tight font-bold text-gray-900 sm:text-4xl sm:tracking-tight pt-">Création d'un evenement</h1>
	</div>

	{{ form_start(form) }}

	<div class="relative flex w-full flex-wrap justify-center items-stretch my-8">
		<div>
			<p class="text-base font-medium text-gray-500">Titre de l'événement</p>
			<span class="z-10 h-full leading-snug font-normal text-center text-slate-300 absolute bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
				<i class="fas fa-lock"></i>
			</span>
			{{ form_widget(form.title, {'label': 'Titre','attr': {'class':'px-3 py-3 placeholder-slate-300 text-slate-600 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring pl-10'}})  }}
		</div>
	</div>
	<div class="relative flex w-full flex-wrap justify-center items-stretch my-8">
		<div>
			<p class="text-base font-medium text-gray-500">Contenu de l'événement</p>
			<span class="z-10 h-full leading-snug font-normal text-center text-slate-300 absolute bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
				<i class="fas fa-lock"></i>
			</span>
			{{ form_widget(form.content, {'label': 'Contenu','attr': {'class':'px-3 py-3 placeholder-slate-300 text-slate-600 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring pl-10'}})  }}
		</div>
	</div>
	<div class="relative flex w-full flex-wrap justify-center items-stretch my-8">
		<div>
			<p class="text-base font-medium text-gray-500">Nombre de places à l'événement</p>
			<span class="z-10 h-full leading-snug font-normal text-center text-slate-300 absolute bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
				<i class="fas fa-lock"></i>
			</span>
			{{ form_widget(form.place, {'label': 'Date de l\'évenement','attr': {'class':'px-3 py-3 placeholder-slate-300 text-slate-600 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring pl-10'}})  }}
		</div>
	</div>
	<div class="relative flex w-full flex-wrap justify-center items-stretch my-8">
		<div>
			<p class="text-base font-medium text-gray-500">Date de l'événement</p>
			<span class="z-10 h-full leading-snug font-normal text-center text-slate-300 absolute bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
				<i class="fas fa-lock"></i>
			</span>
			{{ form_widget(form.date, {'label': 'Nombres de places','attr': {'class':'px-3 py-3 placeholder-slate-300 text-slate-600 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring pl-10'}})  }}
		</div>
	</div>

	<div class="relative flex w-full flex-wrap justify-center items-stretch mb-12">
		<button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-orange-brand hover:bg-orange-brand focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
			{% if(editMode) %}
				Enregistrer
			{% else %}
				Ajouter l'envenement
			{% endif %}
		</button>
	</div>

	{{ form_end(form) }}
{% endblock %}

risurei2/templates/home/create_blog.html.twig
{% extends 'base.html.twig' %}

{% block body %}


	<div class="text-center mt-10">
		<h1 class="text-3xl tracking-tight font-bold text-gray-900 sm:text-4xl sm:tracking-tight pt-10">Création d'un article</h1>
	</div>

	<div class="my-24">
		{{ form_start(form) }}

		<div class="relative flex w-full flex-wrap justify-center items-stretch my-8">
			<div>
				<p class="text-base font-medium text-gray-500">Titre de l'article</p>
				<span class="z-10 h-full leading-snug font-normal text-center text-slate-300 absolute bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
					<i class="fas fa-lock"></i>
				</span>
				{{ form_widget(form.title, {'label': 'Titre','attr': {'class':'px-3 py-3 placeholder-slate-300 text-slate-600 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring pl-10'}})  }}
			</div>
		</div>
		<div class="relative flex w-full flex-wrap justify-center items-stretch my-8">
			<div>
				<p class="text-base font-medium text-gray-500">Contenu de l'article</p>
				<span class="z-10 h-full leading-snug font-normal text-center text-slate-300 absolute bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
					<i class="fas fa-lock"></i>
				</span>
				{{ form_widget(form.content, {'label': 'Contenu','attr': {'class':'px-3 py-3 placeholder-slate-300 text-slate-600 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring pl-10'}})  }}
			</div>
		</div>

		<div class="relative flex w-full flex-wrap justify-center items-stretch">
			<button type="submit" class="ml-3 inline-flex justify-center my-10 py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-orange-brand hover:bg-orange-hover focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
				{% if(editMode) %}
					Enregistrer
				{% else %}
					Ajouter l'article
				{% endif %}
			</button>
		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

risurei2/templates/home/eventByUser.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<div
		class="content">{# <h2>Nom de la rubrique : {{rubrique.label}}</h2> #}
	</div>

	{# {% if app.user.admin is defined %}
				    {% if app.user.admin == 1  %}
				        <div class="content">
				            <a href="{{ path('modification_rubrique',{'id' : rubrique.id})}}"><button class="btn btn-success">Modifier la rubrique</button></a>
				            <a href="{{ path('delete_rubrique',{'id' : rubrique.id})}}"><button class="btn btn-danger">Supprimer la rubrique</button></a>
				        </div>
				    {% endif %}
				 {% endif %} #}

	<hr>
	<h4>Annonces de la rubrique :</h4>
	<hr>
	<section class="article">
		{% for event in events %}
			<article>
				<h2>{{event.title}}</h2>

				<div class="content">
					<img src="https://placehold.it/250x250" alt="">
					<p>{{event.content}}</p>
					<p>Postée par
						{{ event.user.firstname }}
						le
						{{event.createdAt | date('d/m/Y') }}
					</p>

					<a href="{{path('show' ,{'id':event.id})}}" class="btn btn-primary">Voir l'annonce</a>

					{# {% if app.user.admin is defined %}
																					{% if app.user.admin == 1 %}
																						<a href="{{path('annonce_edit' ,{'id':annonce.id})}}" class="btn btn-warning">Modifier l'annonce</a>
																						<a href="{{path('annonce_delete' ,{'id':annonce.id})}}" class="btn btn-danger">Supprimer l'annonce</a>
																					{% endif %}
																				{% endif %} #}

				</div>
			</article>
			<hr>
			<hr>
		{% endfor %}

	{% endblock %}

risurei2/templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HomeController!
{% endblock %}

{% block body %}

	<main class="lg:relative">
		<div class="mx-auto max-w-7xl w-full pt-16 pb-20 text-center lg:py-48 lg:text-left">
			<div class="px-4 lg:w-1/2 sm:px-8 xl:pr-16">
				<h1 class="text-4xl tracking-tight font-bold text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">
					<span class="block xl:inline">Bienvenue chez</span>
					<span class="block text-orange-brand xl:inline">Risurei</span>
				</h1>
				{# <p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">L'art d'apprécier les animés.</p> #}
				<div class="mt-10 sm:flex sm:justify-center lg:justify-start">

					{% if not app.user %}
						<div class="rounded-md shadow">
							<a href="{{ path('login') }}" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-orange-brand hover:bg-orange-hover md:py-4 md:text-lg md:px-10">
								Se connecter
							</a>
						</div>
					{% else %}

						<div class="rounded-md shadow">
							<a href="{{ path('account') }}" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-orange-brand hover:bg-orange-hover md:py-4 md:text-lg md:px-5">
								Voir vos evenements
							</a>
						</div>
					{% endif %}
					<div class="mt-3 rounded-md shadow sm:mt-0 sm:ml-3">
						<a href="{{ path('show_events') }}" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-orange-brand bg-white hover:bg-gray-50 md:py-4 md:text-lg md:px-10">
							Voir tout les evenements
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="relative w-full h-64 sm:h-72 md:h-96 lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2 lg:h-full">
			<img class="absolute inset-0 w-full h-full object-cover" src="https://images.unsplash.com/photo-1640127249305-793865c2efe1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2003&q=80" alt="">
		</div>
	</main>
{% endblock %}